ble:
  device_name: IR Blaster
events:
  OnConnect:
  - NamedCommand: 'On'
    Delay: 0
  - NamedCommand: Green
    Delay: 2
  HeartbeatStopped:
  - NamedCommand: 'Off'
    Delay: 45
    HeartbeatInterval: 15
  Active:
  - NamedCommand: Red
    Delay: 0
  Idle:
  - NamedCommand: Green
    Delay: 75
